### ISSUE TITLE
Is it use file-base db, like txt?

### ISSUE THREAD

**Issue by Hamusuta0320** [Pittow/qq8e-DB#1]

**Comment by Pittow** [comment]
It is file-based , but not a text .

Every number will takes 5 bytes at the beginning . After sortting by QQid , it can be storaged by binary-indexed tree . Most of value will be so small to compress . Just like the description in Readme .

**Comment by Pittow** [comment]
Sorry for the late reply . And since I am so lazy , the code is still debugging .

**Comment by Hamusuta0320** [comment]
Haha. looking forward to the code.
